### ISSUE TITLE
Isolation scope as a DOM element property other than className

### ISSUE THREAD

**Issue by staltz** [cyclejs/core#226]
_From @staltz on February 1, 2016 15:0_

This idea: https://twitter.com/grahammendick/status/694157785160880128

_Copied from original issue: cyclejs/cycle-dom#95_

**Comment by theefer** [comment]
Really interested in better scoping/encapsulating of Cycle components, as currently I suspect the fact that everything is global isn't necessarily obvious to users and could lead to leaky bugs.

(I'd argue this affects all drivers, not just the selectors in the DOM driver. For example, requests in the HTTP driver.)

I was hoping to try and come up with a solution (i.e. a proof-of-concept driver), rather than complain about it, but just wanted to flag my interest :raising_hand: 

I may have time to try a few things next week, but ideas welcome!

**Comment by laszlokorte** [comment]
@whitecolor and I discussed in gitter the following idea:

* DOM.isolateSink: instead of adding classNames to the scope boundary elements it adds `inserted` and  `destroyed` hooks that notify the DOM driver that an isolation boundary has been inserted or removed.
* the DOM driver keeps track of current isolation boundary elements
* DOM.isolateSources: does not use `select(scopeName)` but looks up the isolation boundary element (stream) for the given scope name and treats it as new root element

* event delegation can still be used but now the listeners can be bound to the isolation boundary elements. So it would be a local event delegation for each isolation scope. The listeners would only need to be reattached if an isolation boundary element changes (and only for that element)

I think it would also solve https://github.com/cyclejs/core/issues/229 because event's would naturally bubble from isolation boundary to isolation boundary.

I am not sure if I am missing something.

The hooks that get attached to the boundaries do not care about event handling them self but just notify the driver that boundaries have been created or destroyed.

**Comment by staltz** [comment]
> event delegation can still be used but now the listeners can be bound to the isolation boundary elements.

Very different and interesting approach, I'm curious about trying it out.

> DOM.isolateSources: does not use `select(scopeName)` but looks up the isolation boundary element (stream) for the given scope name and treats it as new root element

One of the benefits of `select(scopeName)` inside `DOM.isolateSource` is it's easy to explain to people how they could manually build isolation, and that isolateSource is just a helper. How do you think that aspect will become? I suppose conventional manual isolation with classnames will still be possible, anyway.

**Comment by laszlokorte** [comment]
> One of the benefits of select(scopeName) inside DOM.isolateSource is it's easy to explain to people how they could manually build isolation, and that isolateSource is just a helper. How do you think that aspect will become? I suppose conventional manual isolation with classnames will still be possible, anyway.

You could expose the `selectScope` method on the DOM object that does exactly that: selecting a scope boundary element by it's scope id. That could be used without `isolateSource`.

You could still use `select()`ing by classes to introduce the concept of isolation.
Then explain that using class names for managing scopes is not desired therefor this specialized method exists and that it looks up elements in a map of scope boundaries.

I just noticed that duplicate scope names could even be detected by checking if an element with an id already exists in the map.

**Comment by whitecolor** [comment]
I belive this should be a param to makeDOMDriver defining what method of Isolation should be used.

> I just noticed that duplicate scope names could even be detected by checking if an element with an id already exists in the map

Right just check the keys. But there is to options how to act in this way: either to `throw`, or implement ablitity to have to elements in the map under "the same" scope value, like it is now for case of classes.

**Comment by laszlokorte** [comment]
> I belive this should be a param to makeDOMDriver defining what method of Isolation should be used.

Assuming the hook approach works. Why would one still want to use the class approach?

**Comment by whitecolor** [comment]
Probably not if he won't wont "ablitity to have to elements in the map under "the same" scope value" wich classes now provider, but so could be done with hooks, I'm not sure if it is a correct behaviour.

**Comment by whitecolor** [comment]
I think people will be glad to have it without foreign classes that mess with their "masterpiece markup")

**Comment by milankinen** [comment]
**[This](https://github.com/cyclejs/core/issues/204#issuecomment-189175529)** relates

**Comment by whitecolor** [comment]
Think `hooks` will be more simple and better way then using "Widget", besides snabbdom doesn't have such. 

And probably this:

> The second drawback is that dom sink just "stops" emitting vtree changes, thus making post-dom transforms (like animations) impossible or at least very challenging.

won't be actual.

**Comment by laszlokorte** [comment]
@whitecolor Actually I just noticed hooks in virtual-dom only support "oncreate" not "ondestroy" so widgets would indeed be needed. But I think snabdom has ondestroy hooks that could be used.

**Comment by whitecolor** [comment]
there is `unhook` it is just not documented.

**Comment by milankinen** [comment]
I'm not so familiar with `virtual-dom` but how about if the component returns `Widget` instead of normal `VNode`? Can you still attach hooks into it?

**Comment by whitecolor** [comment]
@milankinen if it is Widget then need to override its `init` and `destory` methods.

**Comment by staltz** [comment]
Cycle.js used to have the so-called "custom elements" which was a React-like component system based on `Widget` and with isolation built in. We deprecated that and we're not going back to it so soon. Or perhaps ever.

**Comment by milankinen** [comment]
@staltz please read the code again.

**Comment by whitecolor** [comment]
Definitly there will be no any ineed any kind of cumbersome `custom elements` thing in cycle.

**Comment by milankinen** [comment]
@whitecolor Might work! But is it simpler than wrapping the vtree with another widget?

**Comment by whitecolor** [comment]
@milankinen why it should be simplier? hooks allo minimall changes to retunred vtree. and snabbdome has only `hooks` anyway. actually vdom Widget is kind of strange thing to me. snabbdom hooks do all it allows and more.

**Comment by milankinen** [comment]
@staltz Please read the code first and comment after that. My proposal wasn't comparable to React's component system at all - it was just a way to optimize the output stream events.

That said, I agree with you. Isolation is not the right place for such optimization. However, you need to add that somewhere at some point if you want to solve Cycle's performance problems.

**Comment by whitecolor** [comment]
@milankinen the only case I can think where wrapper is needed is when component returns array of elements without root one. But maybe this should be just unhandle case for isolation.

**Comment by whitecolor** [comment]
@milankinen what code, and what there shoud be seen?

**Comment by milankinen** [comment]
@whitecolor For `snabbdom` it'll definitely be simpler. But for `virtual-dom` driver, the isolation must accept also `Widget` type vtrees somehow

**Comment by laszlokorte** [comment]
@whitecolor Currently vtree$ can not an array anyway.

**Comment by milankinen** [comment]
Personally I advocate simplicity - if hooks are simpler options, I'll go for them. My link was just to give you a reference (from one month ago) that might help you with the "official" implementation

**Comment by whitecolor** [comment]
@milankinen As I've said for Widdget its `Widget.prototype.init` and `Widget.prototype.destory` should be used instead of hooks.

@laszlokorte Yes I know you can not give to driver but you can get it as a part of another tree, but its not the case of `component` really.

**Comment by TylorS** [comment]
This is actually done in @cycle/dom v10

**Comment by TylorS** [comment]
Closing for now :)
