### ISSUE TITLE
A couple of old peer dependencies could do with updating

### ISSUE THREAD

**Issue by SteveALee** [cyclejs/core#264]
Following cause peer dependency issues and so may break in npm 3

* eslint-plugin-cycle wants eslint@1.x.x latest is 2.3.0
* cyclic-history@0.1.0 wants history@^1.17.0 latest is 2.0,.1

I'm not sure if I should be using the eslint plugin or extension or both?

**Comment by chadrien** [comment]
> * eslint-plugin-cycle wants eslint@1.x.x latest is 2.3.0

This issue was addressed in cyclejs/eslint-plugin-cycle#1, but no new release of `eslint-plugin-cycle` have been made since the PR was merge. @staltz may simple have forgotten to.

> * cyclic-history@0.1.0 wants history@^1.17.0 latest is 2.0,.1

`cyclic-history` is not a cyclejs project, this one is from @TylorS. Cycle has its own [history driver](https://github.com/cyclejs/cycle-history) which also have a dependency set to `history@^1.x.x`. For both case, I assume (but cannot be sure) that it's because they were built against `history` 1.x and some tests should be required to ensure that changing to 2.x won't break anything as it's a major version (meaning it can contains breaking changes).

**Comment by SteveALee** [comment]
@chadrien Sorry for the noise about cyclic. Somehow I missed it was not cycle :(

I made a not of a few more changes required for elsint2 in cyclejs/eslint-config-cycle#3

I guess that might not be the right place given other repos do not have issues in lue of central tracker

**Comment by staltz** [comment]
Hi and thanks for your time

Cyclic-history is not yet an official cycle repo/lib. Maybe someday it will. ESLint config will be deprecated because we will use TypeScript in Cycle.js internal code.

**Comment by SteveALee** [comment]
OK. I understand ESLint are working on TS support but 'till then we only have TSLint.

Can you / do you produce typings? I don't use TS (yet) but VS Code uses them for Javascript intellisense so they are really useful now. Someone said they can some how be included in the library / module.

I can ass a new issue for the typings if that helps

**Comment by staltz** [comment]
Typings will be added automatically since the whole codebase will be written in TS.

**Comment by SteveALee** [comment]
Great, us there a milestone for that?

**Comment by staltz** [comment]
https://github.com/cyclejs/core/issues/196

**Comment by SteveALee** [comment]
Great, so TS is next step! Something to look at at cycleconf?
