### ISSUE TITLE
Consistent isolation behavior of HTTP driver.

### ISSUE THREAD

**Issue by laszlokorte** [cyclejs/core#272]
Currently the isolation behavior of HTTP driver differs from the behavior of the DOM driver:

```es6
const main = ({DOM, HTTP}) => {
  const child = isolate(ChildComponent)({DOM, HTTP});

  const ownRequests$ = O.just(...); 
  const state$ = model(...);
  const vtree$ = view(state$, child.DOM);

  const responses$ = HTTP.flatMap((r$) => ...);
  const elements$ = DOM.select('.foo').observable;
 
  return {
     HTTP: O.merge(ownRequests$, child.HTTP),
     DOM: vtree$,
  };
};
```

`responses$` will contain both the requests `main` itself made and the requests `child` made.
On the other hand `elements$` with only contain the the `.foo` elements that `main` itself created and not the `.foo` elements that the child created.

Obviously the DOM driver behaves as expected: The main component should explicitly not be able to access the `.foo` elements of the child.

I argue that the same should be true for `responses$`: It should only contain the requests that were made be `main` itself.

Since `main` needs to provide the requests to `child` the `HTTP` object should still contain all the child requests as well but still separate for example in `HTTP.all`.

The sources are already behaving correctly:
`vtree$` contains both the `child.DOM` vnodes and the own vnodes of `main`.
`O.merge(ownRequests$, child.HTTP)` contains both the own requests and the child requests.

`HTTP.isolateSource` should build a new HTTP object like:

```es6
HTTP.isolateSource = (HTTP, scope) => {
  const newHTTP = HTTP.all.filter(exactScope(scope));
  newHTTP.all = HTTP.all.filter(exactOrChildScope(scope));
 
  return newHTTP;
};
```

So `HTTP.all` does not contain *all* requests of the application but only the one of the current component and it's children.

@whitecolor

**Comment by whitecolor** [comment]
So it is actually not so breaking, usually parent has no intentes to handle child requests.

**Comment by staltz** [comment]
@laszlokorte  
> Since main needs to provide the requests to child the HTTP object should still contain all the child requests as well but still separate for example in HTTP.all.

You mean response, not request, right?

**Comment by laszlokorte** [comment]
HTTP itself is a meta stream of responses right? So it's a stream of requests. But yes `response$$` to be exact.

**Comment by staltz** [comment]
Ok, I see how you think of it, I just call it `response$$` or `sources.HTTP` or HTTPSource.

I'm thinking about this proposal. On one hand it doesn't differ from the DOMSource because the latter is always consumed with a `.select().events()`. In a theoretical sense, if you wouldn't call `.select().events()` on the DOMSource, you would get all possible events from the DOM. On the other hand, `DOMSource.select()` has isolation built in, and we don't have an equivalent for the HTTP driver.

Don't bother my bikeshedding, I'm just trying to be thorough, so can you point out a case where the current HTTP driver was unintuitive and presenting problems because of this?

One thing I try to maintain is the abstraction purity, where all read effects (for both the parent and the child) have to pass through the parent. It helps to think of a driver source as a raw resource that is passed down the hierarchy and progressively filtered as it goes down the hierarchy. It's not good if it's a magical resource which behaves differently depending on who queries it in the hierarchy.

One of the benefits of sources and sinks requiring explicit handling/routing to and from its children is the opportunity to do preprocessing and postprocessing. Think: being able to process responses at the parent level before sending them to the child. Or postprocessing a vdom$ sent by a child. The latter could be done for accomplishing overlay tutorials[1]. These kind of things I try to keep in mind.

So I'm leaning more towards the default being what it currently is, and perhaps adding a helper like `sources.HTTP.own` which has only response$ originated by the current component (the parent). It would also be a non-breaking change.

[1] This is something I have been wanting to demonstrate but is still a bit annoying given how virtual-dom and snabbdom vtrees work. These libraries don't provide an easy way of changing a vtree without using mutation which would create weird issues elsewhere. We would need something like React's cloning of the tree.

**Comment by whitecolor** [comment]
> So I'm leaning more towards the default being what it currently is, and perhaps adding a helper like sources.HTTP.own

This is good option, in dom driver I would perefer to have something like this. Because I too see isolation it isolation from siblings, not parent, but DOM driver work another way currenlty, but maybe i'm missing something about DOM.

**Comment by milankinen** [comment]
> So I'm leaning more towards the default being what it currently is,

Couldn't agree more. HTTP driver is an idiomatic Cycle driver.

> but DOM driver work another way currenlty

+1. DOM driver is an idio(ma)tic Cycle driver.

IMHO, the title of this issue should be changed to "Consistent isolation behavior of DOM driver".

**Comment by whitecolor** [comment]
> +1. DOM driver is an idio(ma)tic Cycle driver. 
:smile:

**Comment by laszlokorte** [comment]
I agree that ultimately the current behavior of the HTTP driver is simpler and probably the desired one.

I just think that the inconsistency makes it harder to grasp the concept of isolation.


```
const clicks$ = DOM.select('.foo').events('click');
// is empty if the parent ITSELF has no element with class foo
```
You would not want receive click events on elements that you have not created your self. That's how understood the isolation requirement for the DOM driver and I think that should not be changed.

```
const url = new RegExp('http://foo.io/status');
HTTP.filter((r$) =>
  url.match(r$.url) 
).flatMap((r$) => r$.catch(O.just("error")))
// may be not empty even if parent ITSELF did not request anything
```

Now I think that is an inconsistency that makes it hard to understand what exactly isolation does.

If I ask you: What does isolation is good for?
Answer A: I prevent's sibling components from messing around with each other's stuff
Answer B: I prevent's sibling components and child/parent components from messing around with each other's stuff

If A: cool, then why can a parent not access it's child elements and events?
If B: cool, then why does a parent see all the http responses of it's children by default?

Final answer: Well, the drivers can do whatever they like to do.
(which is technically correct because that's how `isolateSink` and `isolateSource` are implemented, but it does not help grasping isolation)

----

Ultimately I do not care too much about this as I understand your reasoning. It's just a though triggered by all this isolation discussion in the other issues. I suspect that these inconsistencies and the question what isolation actually means and what it should do and what it should not do contribute to all those "conflicts" in the other discussions.

**Comment by staltz** [comment]
> but it does not help grasping isolation

Agreed, what I'm looking for is

> a case where the current HTTP driver was unintuitive and presenting problems because of this?

And

> If B: cool, then why does a parent see all the http responses of it's children by default?

Because I want to try keeping the possibility of preprocessing responses.

But I'm not giving a final answer here. I'm still thinking about it.

**Comment by whitecolor** [comment]
Maybe **Shadow DOM** and give some thoughts about proper isolation for cycle
http://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-301/

> Event Model
Some events cross the shadow boundary and some do not. In the cases where events cross the boundary, the event target is adjusted in order to maintain the encapsulation that the shadow root's upper boundary provides. That is, events are retargeted to look like they've come from the host element rather than internal elements to the Shadow DOM.

**Comment by staltz** [comment]
We've once contemplated that when we had custom elements, but now that everything is done with pure logic in the app code, it's not an option, not to mention the problems with SDOM's adoption in browsers. But it couldn't help with the HTTP driver, right?

**Comment by whitecolor** [comment]
Custom elements is unnesessary thing, I posted it here becase shadow DOM is too just component isolation idea. So how it works with event: events that are seen by (propagated to) parrent components, but event source (target) is isolated element itself, not target that is see within it. And in DOM driver currently parent doesn't see isolated events at all. It is related question should or not isolated events be available to parent via `DOM.select().events`

**Comment by staltz** [comment]
Downgrading this to a discussion until we reach consensus on what to do, otherwise it looks like there's an immediate task to be done.
