### ISSUE TITLE
State handling in Cycle

### ISSUE THREAD

**Issue by Cmdv** [cyclejs/core#280]
following on from [this issue](https://github.com/cyclejs/core/issues/204) which diverged into something entirely unrelated I have created a new location where the discussion can continue about handling state within Cycle.

You can pick up where things started to diverged [here](https://github.com/cyclejs/core/issues/204#issuecomment-199302608).

**Comment by HighOnDrive** [comment]
So this is now the discussion while the other (see link above) remains an issue, interesting. All the great discussion is in the former issue and there might not be to much left to say here, only do. None the less I've got to keep rockin' here. 

Really digging Helsinki more these days, Cycle.js, Calmm-js, Stanga and TSERS all hail from the same place, hows that for progress knowing no bounds!

**Comment by HighOnDrive** [comment]
State management has been an ongoing problem in Cycle for ages. Paste this text "I guess that part is a trade-off of this architecture... " from from Sep 7, 2015 into the cycle-core gitter search to see a interesting conservation about "a miracle solution", "not feeling to bright at the moment" and the "god component". The following gitter link can also be used to time-travel back to the conversation:

:point_up: [September 7, 2015 2:39 PM](https://gitter.im/cyclejs/core?at=55ede7e3fd02f8cd4d2f8eb7)

**Comment by ivan-kleshnin** [comment]
1) `main` and components are stucturally the same [**(fractality)**](http://staltz.com/unidirectional-user-interface-architectures.html)
2) it's [**canonical**](https://egghead.io/lessons/rxjs-exporting-values-from-components-through-sinks?series=cycle-js-fundamentals) to expose value (state!) from components
3) it's [**not canonical**](https://github.com/cyclejs/core/issues/204) to expose state (value!) from main

:fearful:

At what moment [hacks with macros](https://github.com/cyclejs/core/issues/170) were considered to be a better solution?

Should I provide a list of arguments why macros are inherently bad and everyone should avoid them?

**Comment by staltz** [comment]
Isn't it straightforward to use proxy Subjects? Just 2 more lines of code.

**Comment by ivan-kleshnin** [comment]
Derived states perform better as streams. They should also be cycled over... 
I've been experimenting with different app architectures and the more streams I use, the better it goes.
I'll put an article (or even video) on this subject soon.

**Comment by staltz** [comment]
Ok, but I don't understand what "derived states" has to do with proxy Subjects.

**Comment by ivan-kleshnin** [comment]
It's hard to explain all that shortly. Terminology is not consistent, etc. 
But in short: in complex (real) app there are reactive deps in-between what we suppose to be a "state".
If we put all that in one reducer (one stream) we lose reactivity. And get back all the problems of passive programming. 

I've also got serious evidence that navigational stuff (like `window.location.pathname`) should never be put into the state. It should be a separate stream. Which also should be cycled over the main.

So we're ending up with multiple `Subject`s anyway. Or with passive programming.
Or with macros. Or with multiple noop loops. 

I'm in favor of the latter, obviously.

**Comment by staltz** [comment]
I think I get your point about losing reactivity in between state pieces. IMO passive programming is useful for a very few things. One of them is data structures and updates, which includes ES6 Map, Set, and Immutable.js data structures. Reactive programming is still good as the overall structure for changes flowing in the app.

Noop loops or Subjects, both are almost the same thing in "cost", but noop drivers are not semantically "external world communication". Proxy Subjects on the other hand are a local solution.

**Comment by ivan-kleshnin** [comment]
> Noop loops or Subjects, both are almost the same thing in "cost", but noop drivers are not semantically "external world communication". Proxy Subjects on the other hand are a local solution.

Right. But as I later decide to cache state in localStorage (every 100 state changing events) those `identity` function(s) will turn into a `localStorage` or `history` driver(s). Without any change in the app architecture.

**Comment by staltz** [comment]
That is neat indeed :)

**Comment by whitecolor** [comment]
If you will need circular dep inside some function that is supporsed to be a reusable component how are you going to implement it without proxy subject? Would you impose a requirement thtat you should pass somehow internal data around this component?

If you its maybe reasonable to pass data/actions/event though some driver to save it in storage or something like that but not in all cases, mostly it will look redundant and wierd. Proxy is just implementation detail for implementing cyclic dataflow but without drivers (implicit inputs/outputs) involved.

**Comment by HighOnDrive** [comment]
@whitecolor Sounds like your only thinking in terms of a bound and boxy use case for small apps or kitchen sink components that need to loop some data around once in a while, is this what Cycle is about?

What we're really heading for here is data driven apps, you know, always connected cloud based massive and everywhere apps. You can actually learn to think this way (reactive at scale) if you have something of SCALE in mind, at the very least there is plenty of inspiration all around us in this internet age, go make something BIG.

As for components lets think. They are essentially a bit of markup (pick your flavour) and part of the view. What do we know about the view now, oh it's just a function of state! If this is really true then what if we have our data on the cloud? Could we not fill the dumb ass components with wonderful data? Hey, we could even generate components from data, now we are move'n and grove'n. 

So, what are components anyways, if not just silly adapters, just like drivers. They are ways to interface to a DOM or other service points. If you reduce it all down you can get by with only a app shell, a set of processors, which you can linkup as required in a given component (or even generate the links and fill that too) then just feed them state. It's so amazingly wonderful and powerful. Hopefully, we are not still thinking of starting another component shop in this day of the reactive cloud and reactive processing!

Reactive is "neat indeed" if we can stop thinking in yesterday mode :100:

**Comment by HighOnDrive** [comment]
Would it help to list the scenarios for data and it's state in reactive architectures that use circuits? I'm going to do that here because it seems to have be hard to see through the levels of usage, looking at how it has been discussed so far. This is super straightforward and just so we can get on the same page about state management.

Here then are the scenarios:

1) Projected data contained in observables coming from intents or HTTP requests.
2) Proxy subjects used when a nested component requires it's own feedback loop.
3) Local atom model an app might use in conjunction with optional partial lenses.
4) Local storage an app might use to manage multiple atoms with optional lenses.
5) Remote database that is queried and updated from the app with optional lenses.

AFAIK the 2nd scenario also requires a Babel plugin to handle resulting circular dependencies.

It seems to be #3 that is most misunderstood, it could be argued that #1 and #2 might already manage it's purpose, yet it might work for a given app. I think everyone can agree that #4 and #5 would be exceptable use cases for drivers.

Is it correct then to agree that it is #3 we are having a discussion about and what the debate is about? It looks like #3 is in the middle, with proponents of #1 and #2 saying it can handled by #1 and #2 and there is no need for it. On the other side we have #4 and #5 who have no problem allowing #3 to be a member of their driver family.

Could it be this discrepancy simply borders on the grey area of what is counted as a side effect and what is not? There are even cases for single LOC drivers and likely almost everything is an effect of one type or another.

IMO #3 is a valid use case and should be welcomed as such. Doing #3 as a driver makes it more useful, because it can then be a source used throughout the app. This is what Stanga (https://github.com/milankinen/stanga) is about then, moving past #1 and #2 to #3 and onwards to #4 and #5 until all scenarios are covered.

Hope that makes sense! Now, I'm going to dive back into all the great activities going down at the 2nd International Web Audio Conference starting today :dart:

**Comment by whitecolor** [comment]
> Sounds like your only thinking in terms of a bound and boxy use case for small apps or kitchen sink components that need to loop some data around once in a while, is this what Cycle is about?

Any large app contains of small building blocks. I'm sure that if would bother to write some code with cycle it would become much cleaner for you how to solve those tasks that you are struggling to solve on paper. And babel plugin for proxy is completlty opt-in it is not required.

**Comment by HighOnDrive** [comment]
Long before they build an actual bridge they figure it out. Cycle it self is still completely opt-in and parading about with the emperors new cloths, not having sought out the conclusions to it's own pattern.
