### ISSUE TITLE
Discussion: Improved handling and passing of sources between components

### ISSUE THREAD

**Issue by axefrog** [cyclejs/core#284]
Passing the sources object around is kind of a "damned-if-you-do, damned-if-you-don't" scenario. On the one hand, it's nice when you can use destructuring, like so:

```js
function main({DOM, router}) {
  // But now I can't pass sources to child components
}
```

On the other hand, it's important to be able to pass sources around:

```js
function Component(sources) {
  // ...
}

function main(sources) {
  const sinks = Component(sources);
  // But now I have lost the convenience of destructuring
}
```

This brings me to my next point. It's important to be able to pass adhoc streams of data to child components, with common examples such as `props$` or `state$`, but then you have to break the standard component contract, `function Component(sources)`, by supplying additional arguments, and even then, you still lose the ability to simultaneously destructure and pass sources around. To maintain the standard component function signature/contract, you have to contaminate the sources object with component-specific data such as streams of props, and the component must then take that into account when it passes the sources object to its own children. Should it just pass the contaminated sources along as-is and hope for the best, or should it try to sanitize the sources object before  passing it along, and if so, how does it know which sources to keep and which to discard?

I've been experimenting with an approach to possibly conquer all of these issues at once, but I'm curious how others feel about the idea. On one hand, it allows for consistent sources-passing, a consistent single-argument component function contract, the ability to destructure, and provides a way to sanitize or customize sources before passing them to children, but on the other hand, it requires any component that makes use of the technique to assume that all of its ancestors (i.e. other component functions already on the stack) to also either opt in, or to at least not butcher the sources object before passing it on.

Here's what it looks like:

```js
Cycle.run(main, {
  // drivers
});

function main(sources) {
  return App(upgradeSources(sources)); // Say hello to the `upgradeSources` function
}

function App({ DOM, router, sources }) {
  // Note that we get destructuring AND the sources object
  
  function props$ = ... // Make a stream of props for our child component
  function state$ = ... // Get some kind of state from somewhere

  // Pass along a new sources object, upgraded and augmented for the child component
  return SomeComponent(sources.with({ props$, state$ }));
}

function SomeComponent({ DOM, props$, state$, sources }) {
  // `sources` is a recursively-nested copy of `arguments[0]`, so that it can be
  // passed to local functions
  
  // ... Assign foo$ and bar$ some values
  let foo$, bar$; // (Assignment omitted for brevity)

  // Provide YetAnotherComponent with foo$ and bar$, but not props$ or state$
  const yetAnotherChild = YetAnotherComponent(sources.with({ foo$, bar$ }))

  // This one doesn't require any special properties, so create a clean sources
  // object, minus extraneous properties (same as calling `sources.with({})`)
  const anotherChild = OtherComponent(sources.sanitize()); 

  return // ... return sinks as usual
}
```

The implementation is as follows:

```js
export function upgradeSources(sources) {
  const sourceKeys = Array.from(Object.keys(sources));

  const cleanSources = sources => sourceKeys
    .reduce((acc, key) => (acc[key] = sources[key], acc), {});

  function withCustom(baseSources, customSources) {
    const cleanedSources = cleanSources(baseSources);
    const nextSources = Object.assign({}, cleanedSources, customSources);
    return augment(nextSources, cleanedSources);
  }

  function augment(nextSources, cleanedSources) {
    let augmentedSources = Object.assign({
      sanitize: function() {
        return augment(cleanSources(this));
      },
      with: function(custom) {
        return withCustom(this, custom);
      }
    }, nextSources);
    return Object.assign(augmentedSources, {sources: augmentedSources});
  }

  return augment(sources);
}
```

One might argue that it's better to just keep everything super simple and not use these sorts of abstractions. A counter-argument would be that the reason people have pain points at all with Cycle is because of a lack of basic, consistent abstractions for situations like these, leading to a lack of clarity about how to handle issues such as those I described in this topic.

I realise there is an issue when it comes to isolation in that the nested `sources` property would lose homogeneity with isolated sources, but I'm not going to implement a solution to that without further discussion on the main idea itself.

Thoughts/feedback?

**Comment by staltz** [comment]
I think this is the ideal type of API to put in a library and use it as an intermediate/advanced tool.

As you said, we can accomplish whatever we need with the current API, but it may be a bit more verbose. Here are some solutions with vanilla Cycle.js that are more verbose than `upgradeSources`:

**single `sources` argument plus destructuring:**
```js
function main(sources) {
  const { DOM, router } = sources;

  // use DOM and router, or sources
}
```

**grandchild gets all sources except those specifically meant for the child:**
```js
function SomeComponent(sources) {
  const { DOM, HTTP, props$, state$ } = sources;
  // ...

  // Manually list the acceptable sources for the grandchildren
  const yetAnotherChild = YetAnotherComponent({ DOM, HTTP });
  // ...
}
```
**OR**
```js
const omit = require('lodash/fp/omit');
// It's not Cycle's job to do proper FP with objects, so we can import lodash or
// Immutable.js to help us here. Anyway, a Cycle app in production should have
// either one of those, or both.

function SomeComponent(sources) {
  const { DOM, props$, state$ } = sources;
  // ...
  const yetAnotherChild = YetAnotherComponent(omit(sources, ['props$', 'state$']));
  // ...
}
```

> you have to contaminate the sources object with component-specific data such as streams of props

I don't share the opinion about "contamination". There is nothing dirty about props stream, and the top-level sources that come from Cycle.run are not the "pure" sources. Sources are simply dataflow inputs to a function (a dataflow component).

> or should it try to sanitize the sources object before passing it along

We should try to sanitize the sources object before passing it along. It's the current component's responsibility to build the sources that its child needs.

> and if so, how does it know which sources to keep and which to discard?

Sources and sinks are contracts, they should be publicly known. Think of types in functional programming like in Haskell for instance. Whenever you use a function, the code using it has the responsibility to provide the correct arguments. The contract of the function is public, no matter what API or library you are using. It's not the function's responsibility to do guess work in order to capture its own parameters from the given argument. For that reason, it's important that all components specify publicly what sources they expect and what sinks they produce. It's just a function https://en.wikipedia.org/wiki/Type_signature

That said, as you can see, my snippets are a tiny bit more verbose than your helper. So it makes sense to publish it as a separate library.

**Comment by axefrog** [comment]
Regarding:

> I don't share the opinion about "contamination". There is nothing dirty about props stream, and the top-level sources that come from Cycle.run are not the "pure" sources. Sources are simply dataflow inputs to a function (a dataflow component).

Of course, my use of the word "contamination" was simply with respect that passing through a props stream for a component is *probably* only relevant for that component, and it's going to need to strip it out again for any of its children, or leave itself open to unexpected side effects if those children can also take an optional props stream input. The same argument applies to a state stream or anything else of a similar nature. 

> The contract of the function is public, no matter what API or library you are using. It's not the function's responsibility to do guess work in order to capture its own parameters from the given argument. For that reason, it's important that all components specify publicly what sources they expect and what sinks they produce.

That's a valid counterpoint. Even so, I worry about the risk you run into where you have some deep hierarchy of components and each component's requirements must bubble up to the root level, making lower-level components more and more brittle as the descendant component graph gets more complex.

> Sources and sinks are contracts, they should be publicly known. Think of types in functional programming like in Haskell for instance. Whenever you use a function, the code using it has the responsibility to provide the correct arguments.

This is true, but I can see possible problems with edge cases when trying to develop an ecosystem of third-party components. Imagine a case where a third-party component provides an enrichment wrapper for your own components. Perhaps you're passing it a list of component functions to be instantiated as its own children depending on props, and it's going to need to know how to correctly pass inputs to those child components. Without a standardized approach for maintaining consistency in the sources object, it will be difficult for it to know how to pass what those child components require.

So, in a sense, I agree that you can definitely keep things simple and just pass things along on an adhoc basis, and in many cases that is probably the right approach. For a larger application though, I think a standard model for maintaining consistency is a good idea, especially if there is any desire to promote an ecosystem of third-party components.

... Playing devil's advocate to my own point above, I suppose it would be possible for the contract described by a third-party component could include the requirement for a function that correctly transposes `sources`, but on the other hand, that seems needlessly fiddly.

**Comment by staltz** [comment]
I think the problems we are discussing here are about the brittleness of dynamic typing in JavaScript, not necessarily a Cycle thing. Because we are really doing FP here, but without the support of a proper type system. When all the contracts are explicit and verified compile-time, you don't have the problems of missing a grandchildren's requirement up the hierarchy, because it won't compile if you miss.

This happens with any other deep hierarchy in FP. For instance the Elm architecture is about deep nesting of Model types and Action types, and because of strong typing, missing those corner cases is rarely a problem.

> standard model for maintaining consistency

Why can't "sources as an object" and "sinks as an object" be a standard model, provided that all components tell what their contract is (e.g. in documentation since JS doesn't have types)?

**Comment by axefrog** [comment]
> I think the problems we are discussing here are about the brittleness of dynamic typing in JavaScript, not necessarily a Cycle thing. Because we are really doing FP here, but without the support of a proper type system. When all the contracts are explicit and verified compile-time, you don't have the problems of missing a grandchildren's requirement up the hierarchy, because it won't compile if you miss.

Sure, though it's an academic point seeing as we *are* using JavaScript, so the tools and techniques we implement are chosen with respect to the environment we have to deal with. I guess you could tell everyone to just use TypeScript.

> Why can't "sources as an object" and "sinks as an object" be a standard model, provided that all components tell what their contract is (e.g. in documentation since JS doesn't have types)?

You can, of course. But then you hit the fiddly, micromanagement issues I described. And those don't have to be considered issues, as you pointed out, but I personally feel uncomfortable with the fact that we still have to surface deep requirements all the way back up the tree, meaning that use of a component at a deep level then forces its concerns onto all of its ancestors. Probably not too much of an issue in many cases I guess, but I suppose the whole point of the idea is that I like clean, minimal code footprints. Less code means that a component is easier to quickly read/scan and ascertain its behaviour. When you're writing effectively the same bits of code all through your codebase, I usually start considering abstracting it away..

**Comment by staltz** [comment]
> I personally feel uncomfortable with the fact that we still have to surface deep requirements all the way back up the tree, meaning that use of a component at a deep level then forces its concerns onto all of its ancestors

I don't feel uncomfortable with this because it's inherent complexity, not accidental complexity. Say you want to use a component `MusicGenerator` deep inside the hierarchy, and this one expects a `MIDI` source. Using it inside a component `Foo` will automatically make `Foo` be a component that expects `MIDI` as a source. The type signatures **have** to change, because now `Foo` is a component that does different things and requires different inputs, generating different outputs. The **contract** and responsibilities have changed.

> Sure, though it's an academic point seeing as we are using JavaScript, so the tools and techniques we implement are chosen with respect to the environment we have to deal with. I guess you could tell everyone to just use TypeScript.

JavaScript hides the types, but they are always there. I am not saying everyone should use TypeScript. I'm just saying the types and contracts are always there. Embracing them is better than hiding them because implicit types and contracts are what really make codebases brittle. If you don't use TypeScript or Haskell, than you need to be extra careful that the contracts are being fulfilled. The responsibility that would otherwise be on the compiler to statically check that for you is suddenly all on your hands. I know JavaScript is a language that allows you to *pretend* that types and contracts are not there, but it only leads to fragile or magical code.

**Comment by staltz** [comment]
Can we have a third perspective here? @edge @TylorS @laszlokorte ?

**Comment by laszlokorte** [comment]
I just destructure the sources object in the parameters:
```
const myComp = ({DOM, HTTP, props$, foo$}) => {
}
```

As you described this forces me to make all child dependencies explicit in the parent's signature and makes all dependencies propagate upwards.

> I personally feel uncomfortable with the fact that we still have to surface deep requirements all the way back up the tree, meaning that use of a component at a deep level then forces its concerns onto all of its ancestors

 I see this as an advantages or rather as the correct way of doing it. Because by not doing so the requirements wont go away but will just be hidden. You would still have to document somewhere that "component X a requires sources: A,B and C and additionally it expects D, E and F to be there because they are needed inside a sub component Y". If you do not do so the usage of component X will lead to an error if D, E or F are not available. So if you have to document it anyway why not just do it right in the signature?

Obviously the root of the issue is the core concept of cycle the idea of "the app/component is a function". If a component is a function or more specific if the usage/setup of the component is equal to the call of that function there is no other way than passing all dependencies down the hierarchy.

A solution could be instead of passing down all the sources a child component needs to pass down the child component itself as a curried function which already has been applied to all of it's global dependencies:

```
// main still needs to specify all dependencies
const main = ({DOM, HTTP, storage, socket, audio}) => {
   const subComponentForA = curried(compB, {storage, socket, audio});
   const ca = compA({DOM, HTTP, subComponent: subComponentForA});
   
   return {
      DOM: ca.DOM,
      HTTP: ca.HTTP,
      storage: ca.storage, // this is weird
      socket: ca.socket, // ...
      audio: ca.audio, // ...
   };
};

const compA = ({DOM, HTTP, subComponent}) => {
   const child = subComponent({DOM, HTTP});

   return {
      DOM: view(..., child.DOM),
      HTTP: ...,
      storage: child.storage, // :-(
      socket: child.socket,
      audio: child.audio,
   }
};

const compB = ({DOM, storage, socket, audio}) => {
  return {
    DOM: ...,
    storage: ...,
    socket: ...,
    audio: ...,
  }
};
```

But this code above is really stupid. You get rid of of the need to pass dependencies for `compB` through `compA`, but `compA` still needs to return all the sinks of `compB`. The sources and sinks of `compA` are not longer symmetric. `compA` would still need to document those additional return values in order to tell `main` to pass them to the drivers. The data flow is really messed up.

So in the end in my opinion there is no other way then making all sources and sinks explicit everywhere if you want to have an explicit and simple data flow.

**Comment by TylorS** [comment]
I've generally chosen to use `sources` only and to liberally use `object-rest-spread`, which I'll still note isn't a standard JS feature, but is possible via babel plugins.

```js
function Component(sources) {
  const {DOM, HTTP} = sources 
  ...
  const props$ = Observable.just(....)
  const something$ = Observable.just(...)
  const otherComponent({...sources, props$, something$})
}

```

**Comment by HighOnDrive** [comment]
I'm really appreciating these types of discussions more now that I know about Clojure, which is the other foundational stone of programming paradigms beside Haskell. It's Haskell that has the strong type system and Clojure where the data is the code. Anyways just interesting because until now I kept hearing that Haskell was this god language when really it is just one of two major approaches.

I certainly like the Clojure approach and having an approach like that would make sources and sinks much more fluid. However, in following the Haskell tradition you end up having to work dataflow through a mess of function signitures. I'm still learning about the differences and found the following article helpful in knowing the difference between Haskellian and Clojurian approaches to moving data around.

https://medium.com/@chetcorcos/functional-programming-for-javascript-people-1915d8775504#.t2t5pon3z

**Comment by sdebaun** [comment]
just saw this via productpains, wanted to share our current approach with sparks... though it has been changing on a weekly basis, here's the kind of stuff we're doing...

Convention we're using so far is:

```js
const FooPageComponent = sources => {
  const bar = BarClickableDisplayComponent({...sources,
    item$: sources.someSpecificSourceFromAbove$,
  })

  const baz = BazCreationComponent({...sources,
    isOpen$: bar.click$.map(true),
  })

  const queue$ = baz.item$.map(aLibraryFunctionThatTranslatesItemToQueueTask)

  return {
    queue$,
    DOM: combineLatest(bar.DOM, baz.DOM, (...doms) => div({}, doms)),
  }
}
```

We are also using the convention that all `sources` are observables, or functions that return observables, which means things like:

```
const hello = ListItem({
  title$: just('Hello World'),
})
```

I agree that the lack of transparency in the component args is not a good thing.  We're trying to solve that by keeping our components as small as possible, so you can easily see where sources is being used in your IDE.

We have already started a collection of easily reusable components, and plan on extracting that into a library soon.  I want to make sure the naming conventions are standardized amongst all components and fill in a couple of holes (notably a TabControl).

https://github.com/sdebaun/sparks-cyclejs/blob/release/src/components/sdm/ListItem/index.js

PRs, Issues, etc welcome on sparks-cyclejs. :)

**Comment by axefrog** [comment]
Thanks for all the great comments, everyone. Your arguments have convinced me.

**Comment by edge** [comment]
**Edit: oops, looks like the issue was closed while I was writing this. I suppose there's still some value in reading it.**

This is a pretty nice idea, but it's a bit too opinionated. With some reduction, I might be more comfortable with using it.

Before anything, `cleanedSources` is not referenced within the body of `augment`, so I'm a little confused.
```js
function augment(nextSources, cleanedSources) {
  let augmentedSources = Object.assign({
    sanitize: function() {
      return augment(cleanSources(this));
    },
    with: function(custom) {
      return withCustom(this, custom);
    }
  }, nextSources);
  return Object.assign(augmentedSources, {sources: augmentedSources});
}
```

First, I think that having `sources` point to itself is not necessary. In the end, it feels more like a hack to make up for the lack of a language feature.

Haskell makes a point of your concern and implements *as-notation*. This allows you to both pattern match (destructure) against the argument while still keeping a reference to the argument itself.
```hs
-- stack dup, duplicates head
dup (h:t) = h : h : t
-- with as-notation
dup s@(h:_) = h : s
```
This saves you the convenience of doing
```hs
dup s = h : s
  where (h:_) = s
```
At the end of the day, one extra line of code isn't really all that bad, and the same argument could be made for Javascript:
```js
function Component(sources) {
    let { DOM, props$ } = sources;
}
```

But I do think that it's useful to explicitly unsubscribe from extra sources. One way of doing that would be to explicitly make components take two arguments, but that would require a breaking change, lest we end up with an ecosystem that could blow up at any second. In that case, we could use a two-element array with the structure `[sources, customSources]`.

```js
function Component([sources]) {
    // ...
}
```
is an explicit out-out, and
function Component([sources, customSources]) {
    // ...
}
```
is an explicit opt-in.
