### ISSUE TITLE
wrapper for making isolated component

### ISSUE THREAD

**Issue by whitecolor** [cyclejs/core#285]
This issue was already created by me once in cycle/isolate repo. @staltz refused it, but I want others to express opinion.

What about including in `isolate` module a helper for making  components be always isolated.
```js
const isolated = (dataflowComponent) => (...args) =>
  isolate(dataflowComponent).apply(null, args)
```

```js
import {isolated} from '@cycle/isolate'

const MyComponent = isolated(({DOM, HTTP}) => {
...
})
```

or it maybe called `makeIsolated`

I understand that is it is just 2 lines of code, but why not include it? Is creating isolated by default components really exessive and undesirable pattern? What do people think about it?

@TylorS @laszlokorte

**Comment by staltz** [comment]
> I understand that is it is just 2 lines of code, but why not include it?

Because it's 2 lines of code also in userland. Not even that, it's a few characters more in userland. 

Non isolated:
```js
function MyComponent({DOM, HTTP}) {
  //...
}
```

Isolated:
```js
import isolate from '@cycle/isolate'

const MyComponent = isolate(function ({DOM, HTTP}) {
  //...
});
```

Compare that to having **isolate** + **isolated**. You know what `isolated` does, but what does a new programmer think about it? He probably thinks something along the lines of:

- *What's the difference?*
- *Which one should I use?*
- *Can't remember which one I want, was it `isolate` or `isolated`?*

By adding a *choice*, we add confusion, a new concept to learn, a new stone to trip over, a character to misread when looking at code, etc.

**Comment by staltz** [comment]
PS, it can also be done when exporting the component

```js
import isolate from '@cycle/isolate'

function MyComponent({DOM, HTTP}) {
  //...
}

export default const IsolatedMyComponent = (sources) => isolate(MyComponent)(sources);
```

**Comment by whitecolor** [comment]
I didn't think about this semantics:
```
const MyComponent = sources => isolate(({DOM, HTTP}) => {
  //...
})(sources);
```
It seems pretty neat.

**Comment by laszlokorte** [comment]
I do not like to isolate my components by default anyway and I agree with @staltz about the confusing naming of isolate(d).

**Comment by whitecolor** [comment]
Well I see that usefull and makes code a little cleaner for some reused componetent that are designed to work isolated:
But is semantic is quite good:
```
export default sources => isolate(OpenReferences)(sources)
```
So closing.
