### ISSUE TITLE
Why do I have to call `isolate` for each instance?

### ISSUE THREAD

**Issue by tusharmath** [cyclejs/core#295]
I was going thru the source code of `isolate` and this particular line made me wonder —

https://github.com/cyclejs/isolate/blob/master/src/index.js#L37
```js
function isolate(dataflowComponent, scope = newScope()) {
  if (typeof dataflowComponent !== `function`) {
 ...
```
why is a `scope` created only when `isolate` method is called? Wouldn't it be a much better API if I could just create an *Isolated* component and whenever I use it — by passing different props, it creates a new scope?

For instance —
**Current:**
```js
  const weightSlider = isolate(LabeledSlider)(weightSources);
  const heightSlider = isolate(LabeledSlider)(heightSources);
```

VS

**Updated**

```js
  const IsolatedLabeledSlider =  isolate(LabeledSlider)
  const weightSlider = IsolatedLabeledSlider(weightSources)
  const heightSlider = IsolatedLabeledSlider(heightSources)
```

Though this can be easily done by using a wrapper function, could it not be a part of the API?

**Comment by laszlokorte** [comment]
Yes you could do it. It's described in the docs as well:
http://cycle.js.org/components.html#Should-I-always-call-isolate-manually

**Comment by tusharmath** [comment]
@laszlokorte Sure, but wouldn't it just make a better API if I din't have to do it with each component?

**Comment by laszlokorte** [comment]
You could achieve it by doing:
```
const isolated = (comp) => (sources) => isolate(comp)(sources)
const IsolatedLabeledSlider =  isolated(LabeledSlider)
const weightSlider = IsolatedLabeledSlider(weightSources)
const heightSlider = IsolatedLabeledSlider(heightSources)
```

But as I said there are cases in which you want to have control over if a new scope is created or not. So your proposed api is not a sensible default behavior because you lose control.

**Comment by tusharmath** [comment]
@laszlokorte How would we lose control? I guess it's just a matter of taste. I don't find the unnecessary use of closure very intuitive. One could do without it and just pass the sources as the third param.

**Comment by laszlokorte** [comment]
@tusharmath You can define the `const isolated = (comp) => (sources) => isolate(comp)(sources)` once in your project and then use `isolated` (with trailing d) instead of `isolate` in your project to get exactly your proposed semantics.

> How would we lose control?
For example in the following case:
```
const mySlider = isolate(Slider);
const myCheckbox = isolate(Checkbox);
const child$ = toggle$.map((showSlider) => showSlider ? mySlider({DOM}), myCheckbox({DOM}))
```

I want to create a child component. It's either a slider or a checkbox depending on some state. That state can change over time. With the current isolation behavior the slider and the checkbox can be recreated multiple times and keeping their scope. With your semantics each time the `toggle$` value changes and a new slider or checkbox is initialized it would get a completely fresh scope. For one that'S unnecessary and second it could lead to wrong behavior: If the slider sends and http request (which is marked with it's scope) and the before the response arrives `toggle$` changes from slider to checkbox and back to slider the freshly created slider will not receive the response because it has been given a new scope id.
I admit that's a pretty synthetic use case but it show's that there are cases in which you want recreate a component without giving it a new scope.

Additionally keep in mind that the `isolate` function take's a second parameter which allows you to specify a custom scope id. In that case your semantics would not work at all.

**Comment by tusharmath** [comment]
@laszlokorte good example not synthetic at all. Thanks!
