### ISSUE TITLE
How to integrate in existing codebase

### ISSUE THREAD

**Issue by Sinewyk** [cyclejs/core#311]
I've not seen any guide/recommandations on how to try cyclejs in an existing code base (brownfield project). React makes it easy, have a DOM node and render into it, it's the first thing you see when looking at their github.io page.

How would we go about trying out cyclejs in a brownfield project ? I've only seen greenfield examples and it's not obvious how to start building stuff in an existing application.

I've not seen the opposite of `run` so that we can clean up everything that what does by run automatically.

Do you have recs or is it just not done or am I missing something ?

**Comment by TylorS** [comment]
```js
const container = document.querySelector('#yourDOMNode')

const {sources, sinks} = run(main, {
  DOM: makeDOMDriver(container)
})

// ready to clean things up
sources.dispose()
sinks.dispose()
```

**Comment by staltz** [comment]
@Sinewyk Thanks for asking. First, note that React is a UI library, while Cycle.js is like Angular, it's a framework and an architecture. This means it mostly makes sense as the only architecture for your application.

That said, there are 3 differents ways of integrating existing code with Cycle.js.

First, is an existing UI component integrated into Cycle.js. For instance a date picker component. This can be done through virtual-dom Widgets or snabbdom hooks. Check the documentation on virtual-dom or snabbdom. Cycle.js supports both of these libraries, but we are migrating more towards snabbdom.

The other is integrating a Cycle.js component into an existing architecture. I'd recommend that would be done through a Web Component, which is a standard of making any framework interoperate with any other. We don't have documenation for that yet, but it's mostly enough to follow Web Component docs.

The third is gradually porting an existing application to Cycle.js. Because Cycle.js has a generic abstraction for communication, this can be done through custom drivers, no matter what your existing application does. You need to just identify: what messages your app will send to the cycle.js part, and what messages cycle.js will send back to your app. Then you can make a source (read-only) driver for the first type, and a sink (write-only) driver for the second type. Read the official cycle.js docs on drivers to get an idea about that.

Hope this helps

**Comment by Sinewyk** [comment]
It does. Thanks.

**Comment by SteveALee** [comment]
One question that comes up often is the interface between imperative and streams based code.
