### ISSUE TITLE
Using pug(jade) for templating in cycle.js

### ISSUE THREAD

**Issue by eskhool** [cyclejs/core#321]
I hope I haven't missed this somewhere (in my googling) but how would one go about using jade as a template language with cycle.js. 

Having done more homework and read (and heard), my question is now more refined to: Can we use https://github.com/tdumitrescu/virtual-jade to generate the virtual dom for cycle.js? Is there anything preventing that from working?

**Comment by whitecolor** [comment]
Theoretically, you could use jade templtes converted in to virtual dom. But I really do not advice you do do so, just use hyperscript helpers, it will make markup code quite clean (cleaner than JSX at least), it will be less error prone, and will give much more flexibility.

Note that in new version of `cycle/dom` `snabbdom` is used instead of `virtual-dom`. So to use virtual-dom you either should use old (actually current yet) `cycle/dom` driver or make `snabbdom-jade` =) which is probably not what you want to do.

**Comment by eshansingh** [comment]
The problem right now is HyperScript is not known by very many people. I don't think it's a good idea for Cycle to restrict itself to HyperScript. But I understand that trying to maintain other templating languages out of the approx gazillion out there will quickly become a nightmare. I suggest that we could create some documentation for how to use some of the other popular ones (Jade, JSX, Handlebars... etc)

**Comment by eskhool** [comment]
I agree. This is not a cycle only issue. Its an issue faced by almost any virtual dom library. A good many to many transpiling framework which can take template formats such as jade/jsx handlebars etc and output various HTML-as-JS frameworks (hyperscript, react functions for JS etc) would be ideal but thats just my wishful thinking

**Comment by eshansingh** [comment]
It would be an interesting project, though. I'll consider it.

**Comment by whitecolor** [comment]
> The problem right now is HyperScript is not known by very many people.

It is not relevant. HyperScript is just HTML written using JS. JSX is supported as it is too just HTML written with clumsy JS-xml. Other string based templates require usage of proper DOM driver, you may just send string and rerender while HTML based on the template but this is not efficient and will work much slower then virtual-dom based libs.

**Comment by TylorS** [comment]
@eskhool It's totally possible, but a little weird in my opinion. 

http://www.webpackbin.com/41XeK048b
